module_name: cascade
train_name: cascade
train_id: default
whisper_name: small
monitor: None
num_nodes: 2
test_batch_size: 5
num_worker: 4
num_train_epochs: 10
gradient_accumulation_steps: 4
chunk_size: 8

data_root: null
cv_data_root: null
output_dir: null

asr_model_path: whisper_small_asr.pt
mbart_model_path: mbart_x_en.pt

avail_lang: 
# - french
# - german
# - spanish
# - italian
# - russian
# - chinese
# - portuguese
# - persian
- estonian
# - mongolian
# - dutch
# - turkish
# - arabic
# - swedish
# - latvian
# - tamil
# - japanese
# - indonesian
# - slovenian
# - welsh
# - catalan



