module_name: whisper
train_name: whisper_tiny
train_id: initial
whisper_name: tiny
monitor: valid_bleu_epoch
data_root: null
cv_data_root: null
output_dir: null
ckpt_name: "checkpoint-{epoch:02d}-{valid_bleu_epoch:.2f}"
use_deepspeed: true
use_acti_ckpt: true
chunk_size: 5
num_nodes: 4
loss_scale: 0

learning_rate: 1.0e-7
lr_end: 1.0e-8
lr_pow: 2.0
weight_decay: 0.1
adam_epsilon: 1.0e-6
adam_betas: [0.9, 0.98]
warmup_steps: 5000
batch_size: 3
test_batch_size: 10
num_worker: 4
num_train_epochs: 10
gradient_accumulation_steps: 4

avail_lang: 
# - french
# - german
# - spanish
# - italian
# - russian
# - chinese
# - portuguese
# - persian
# - estonian
# - mongolian
# - dutch
# - turkish
# - arabic
- swedish
# - latvian
# - tamil
# - japanese
# - indonesian
# - slovenian
# - welsh
# - catalan